//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_VR_project : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean PlayAndPause
        {
            get
            {
                return SteamVR_Actions.vR_project_PlayAndPause;
            }
        }
        
        public virtual SteamVR_Action_Boolean forwardAndBackward_button
        {
            get
            {
                return SteamVR_Actions.vR_project_forwardAndBackward_button;
            }
        }
        
        public virtual SteamVR_Action_Vector2 forwardAndBackward_pad
        {
            get
            {
                return SteamVR_Actions.vR_project_forwardAndBackward_pad;
            }
        }
    }
}
